### PR TITLE
fix: off-by-one in clearObsoleteQueueItems

### LINKED ISSUE #2517: Bug: 0.31.0-rc1 failed upgrade and reset on previewnet
### Description

Previewnet was working fine with version `0.30.0` of BN, once we attempted to do the upgrade flow of blocks stopped, we then attempted a reset, but the flow of blocks was also lost.

we need to fix metrics, since 0.31.0 upgraded to new metrics framework from foundation. so we also need to fix flow of metrics to previewnet.

### Steps to Reproduce

No clear way to reproduce just yet, being investigated so we can create reproduceable TDD tests on BN repo.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlfredoG87**
Fixes #2517 

### Incident

On previewnet `0.31.0-rc1`, BN `lfh01` experienced a total pipeline stall when a CN stopped sending mid-block (sent header + items, never sent end-of-block). This can happen at any time — a CN crash, network partition, or process restart is sufficient to trigger it. Once triggered, the pipeline freezes indefinitely with no recovery:

- **776 blocks silently dropped** (1,175,214 -> 1,175,990) over 29 minutes
- **766 phantom "Completed blocks" increments** — counter climbed while zero blocks were verified, persisted, or ACKed
- **Stalled handler was never evicted** — no timeout, no EndStream, no removal

### Known limitation: stalled handler holds the pipeline

`LiveStreamPublisherManager` has no timeout for incomplete blocks (Bug 1 / #1841 and #2055). When a handler wins ACCEPT for a block and goes silent mid-stream, the forwarder's `queueByBlockMap` holds that block's incomplete queue indefinitely. `determineCurrentBlockNumber()` picks it via `firstEntry()` and the forwarder loops on an empty queue forever. All subsequent blocks are accepted by the decision layer but never forwarded.

### Expected mitigation: LIVE_TAIL greedy backfill

The LIVE_TAIL backfill mechanism was designed to mitigate this. When a peer BN has blocks that the local BN is missing, the backfill plugin fetches them and fires a `PersistedNotification`. The publisher manager's `handlePersisted()` then calls `clearObsoleteQueueItems()` to remove stale queues, unsticking the forwarder. This worked correctly in **v0.30.0**.

### Regression: PR #2419 / #2454 (2026-03-27)

PR #2454 (`chore: Revisit and Update BlockActions Returned by Manager`, commit `b11c8147`) introduced `clearObsoleteQueueItems()` with an off-by-one error:

```java
queueByBlockMap.headMap(blockNumber).keySet()
```

`ConcurrentNavigableMap.headMap(key)` returns entries **strictly less than** `key`. When backfill persists block N and `clearObsoleteQueueItems(N)` is called, block N's stalled queue is **excluded** from removal. The forwarder's `determineCurrentBlockNumber()` picks it via `firstEntry()` and remains stuck forever.

Additionally, if peer BNs are unreachable (restart, network partition, or simply no peers configured), the `autonomousFetcher` can't detect the gap and backfill never fires — leaving the stall completely unrecoverable. Rolling upgrades are recommended to ensure at least one peer is always available.

### Two compounding failures

1. **Backfill unavailable**: If peers are unreachable for any reason -> no LIVE_TAIL gap detected -> backfill never fires
2. **Backfill ineffective even when it fires**: `headMap(N)` off-by-one -> stalled block N's queue survives cleanup -> forwarder stays stuck

### Fix

Change `headMap(blockNumber)` to `headMap(blockNumber, true)` (inclusive), so that when `clearObsoleteQueueItems(N)` is called, block N's stalled queue is included in the removal set.

### Tests

Two new regression tests that reproduce the exact forwarder deadlock:

1. **`PublisherManagerRegressionTest.testForwarderAdvancesPastStalledBlockAfterBackfill`** — Manager-level: pre-loads blocks 0-4, stalls on block 5, backfill persists block 5, asserts block 6 reaches the messaging facility via the forwarder
2. **`StreamPublisherPluginRegressionTest.testForwarderAdvancesPastStalledBlockAfterBackfill`** — Plugin-level end-to-end: streams blocks 0-4 live with ACK verification, stalls on block 5, simulates LIVE_TAIL greedy backfill persisting block 5, streams blocks 6-7, asserts ACK for both

Both tests fail on `0.31.0-rc1` code and pass with the `headMap` fix.

### Remaining work

- **#1841**: Stalled handler timeout detection — the definitive fix for zombie handlers that eliminates the dependency on backfill as a recovery mechanism

### CODE REVIEW

File: block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java [hunk 1]
```diff
@@ -388,13 +388,13 @@ public void handlePersisted(@NonNull final PersistedNotification notification) {
...
-    /// @param blockNumber the latest persisted block number. Only queue
-    ///     entries whose key is strictly less than this value are candidates
+    /// @param blockNumber the latest persisted block number. Queue entries
+    ///     whose key is less than or equal to this value are candidates
     ///     for removal.
     private void clearObsoleteQueueItems(final long blockNumber) {
         if (queueByBlockMap != null && !queueByBlockMap.isEmpty()) {
             final NavigableSet<Long> keysBeforeBlock = new TreeSet<>();
-            keysBeforeBlock.addAll(queueByBlockMap.headMap(blockNumber).keySet());
+            keysBeforeBlock.addAll(queueByBlockMap.headMap(blockNumber, true).keySet());
```
Comment (jsync-swirlds) [inline block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java]: This needs to be reevaluated as clearing queue items has a lot of side effects.
@ata-nas should consider the side effects here and incorporate any additional changes needed into his [current PR](https://github.com/hiero-ledger/hiero-block-node/pull/2505).

**Review by jsync-swirlds — APPROVED** [review]
We need to evaluate this change a bit more thoroughly.
The hotfix is OK, but Atanas needs to make sure we have all the possible side effects covered as well.

**Review by ata-nas — APPROVED** [review]
