### PR TITLE
fix(1523): Prevent Unexpected OutOfMemoryError under high load

### LINKED ISSUE #1523: Unexpected OutOfMemoryError under load
in 100M-accounts SDPT run all BlockNodes crash every 30 mins with OOM, e.g. 

https://perf.analytics.eng.hashgraph.io/ephemeral/test_runs/20642-blocknodes-with-sdpt_AdHoc5_124/report/CryptoTransferLoadTest/podlog_solo-sdpt-n5/block-node-0-b767bb5b8-2qrg4_logs/blocknode-0.log

Memory given to BN process: -Xms16G -Xmx16G

Repro in 30 min in SDPT run

### PR DESCRIPTION
**Pull request by jsync-swirlds**
## Reviewer Notes
* Reduced default queue sizes for block items and block notifications.
   * Notifications, in particular, need to be smaller, mostly because
     blocks at high TPS can be 400M or larger.
* Adjusted values files for helm charts in the
  base values, mini values, and mid-size values files.
* Automatic HPROF dump on error
   * Added requested command line flags

## Related Issue(s)
 May address #1523 and #1540.

### CODE REVIEW

File: block-node/app/docker/update-env.sh [hunk 1]
```diff
@@ -24,12 +24,12 @@ echo "BACKFILL_BLOCK_NODE_SOURCES_PATH=/opt/hiero/block-node/backfill/backfill-s
 
 if [ true = "$is_smoke_test" ]; then
   # add smoke test variables
-  echo "MEDIATOR_RING_BUFFER_SIZE=1024" >> .env
-  echo "NOTIFIER_RING_BUFFER_SIZE=1024" >> .env
+  echo "MEDIATOR_RING_BUFFER_SIZE=512" >> .env
+  echo "NOTIFIER_RING_BUFFER_SIZE=16" >> .env
```
Comment (AlfredoG87) [inline block-node/app/docker/update-env.sh:28]: Are we still using this configurations?? I believe these are legacy and should be removed. would be surprised if any plugin is using them..

File: charts/block-node-server/values-overrides/mid-size.yaml [hunk 2]
```diff
@@ -1,4 +1,18 @@
 resources:
   requests:
-    cpu: "4"
+    cpu: "8"
     memory: "12Gi"
+
+blockNode:
+  config:
+    JAVA_OPTS: '-Xms8G -Xmx8G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp/dump.hprof"'
+    MEDIATOR_RING_BUFFER_SIZE: "256"
```
Comment (AlfredoG87) [inline charts/block-node-server/values-overrides/mid-size.yaml:9]: are we using the mediator prefix?

File: charts/block-node-server/values-overrides/mini.yaml [hunk 3]
```diff
@@ -6,13 +6,15 @@
...
-    cpu: "3"
+    cpu: "4"
     memory: "8Gi"
 
 blockNode:
   config:
-    JAVA_OPTS: "-Xms5G -Xmx5G"
-    MEDIATOR_RING_BUFFER_SIZE: "2048"
+    JAVA_OPTS: '-Xms4G -Xmx4G  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp/dump.hprof"'
+    MEDIATOR_RING_BUFFER_SIZE: "64"
```
Comment (AlfredoG87) [inline charts/block-node-server/values-overrides/mini.yaml:15]: same as above

File: charts/block-node-server/values.yaml [hunk 4]
```diff
@@ -98,18 +98,20 @@ blockNode:
...
     # key: value
     JAVA_TOOL_OPTIONS: "-Djava.util.logging.config.file=/opt/hiero/block-node/logs/config/logging.properties"
-    JAVA_OPTS: "-Xms16G -Xmx16G"
+    JAVA_OPTS: '-Xms16G -Xmx16G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp/dump.hprof"'
     # PRODUCER_TYPE: "NO_OP"
     # PERSISTENCE_STORAGE_TYPE: "NO_OP"
     # VERIFICATION_TYPE: "NO_OP"
     # MEDIATOR_TYPE: "NO_OP"
-    MEDIATOR_RING_BUFFER_SIZE: "8192"
+    # MEDIATOR_RING_BUFFER_SIZE: "512"
```
Comment (AlfredoG87) [inline charts/block-node-server/values.yaml:106]: I think we can safely remove anything referencing the "mediator"

**Review by AlfredoG87 — APPROVED** [review]
LGTM, just some nits related to the same thing.

File: block-node/app/docker/update-env.sh (hunk 1 above)
Comment (jsync-swirlds) [reply block-node/app/docker/update-env.sh:28]: I don't actually know, so I'm keeping it safe in this PR.
I'll file an issue to investigate and remove these if possible.

File: charts/block-node-server/values-overrides/mid-size.yaml (hunk 2 above)
Comment (jsync-swirlds) [reply charts/block-node-server/values-overrides/mid-size.yaml:9]: Nope, copy-pasta error, will fix.

**Review by Nana-EC — COMMENTED** [review]
Agree with Fredy's comments.
One request is to update the Config README with the new defaults

File: charts/block-node-server/values.yaml (hunk 4 above)
Comment (jsync-swirlds) [reply charts/block-node-server/values.yaml]: Done.

**Review by AlfredoG87 — DISMISSED** [review]

**Review by AlfredoG87 — DISMISSED** [review]

**Review by AlfredoG87 — APPROVED** [review]

**Comment by jsync-swirlds** [comment]
Apologies for all the spacing changes in the configuration markdown, that was the result of a spotless reformat.
