### PR TITLE
fix: Send Acknowledgements Only On Successful Persistence

### LINKED ISSUE #1718: Send Acknowledgements Only On Successful Persistence
### Description

- sending acknowledgements is possible on failed verification
- acknowledgements must be sent only on successful verification

### PR DESCRIPTION
**Pull request by ata-nas**
## Reviewer Notes

* Adding success check when handling a persistence notifications
* Adding tests for this logic

## Related Issue(s)

Fixes #1718

### CODE REVIEW

File: block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java [hunk 1]
```diff
@@ -566,13 +566,15 @@ public void handleVerification(@NonNull final VerificationNotification notificat
     public void handlePersisted(@NonNull final PersistedNotification notification) {
         if (notification != null) {
```
Comment (jsync-swirlds) [inline block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:567]: Move the if succeeded here to make this a bit simpler and clearer.
```suggestion
        if (notification != null && notification.succeeded()) {
```

Comment (jsync-swirlds) [reply block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:567]: We can do an if null in the else; which seems more reasonable.

Comment (ata-nas) [reply block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:567]: I personally find that to be error prone. It is easy to miss/neglect yet anotehr null check. I think we should stick with a single point to check if the notification is null and afterwards we are safe to use the reference.

Comment (jsync-swirlds) [reply block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:567]: Fair point.

**Review by jsync-swirlds — APPROVED** [review]
