### PR TITLE
fix(s3-archive): Fixed multiple uploadTask attempts both when range available and unavailable

### LINKED ISSUE #1941: bug(s3plugin): While backfilling UploadTask keeps on failing
### Description

While the BN is catching up in autonomous backfilling the S3ArchivePlugin produces too many logs in failed attempts to upload a batch.

### Steps to Reproduce

Given the following network topology:

```
block_nodes:
    rfh01_test:
        address: <redacted>
        port: 40840
        peers: [s01_test_chicago]
    s01_test_chicago:
        address: <redacted>
        port: 40840
        peers: [rfh01_test]

consensus_nodes:
    us_central:
        block_nodes: [rfh01_test, s01_test_chicago]
    us_east:
        block_nodes: [s01_test_chicago, rfh01_test]
```

BN `s01_test_chicago` already had blocks from `64920000` to `65017285`
when block node: `rfh01_test` came online, with following config override:
```
BLOCK_NODE_EARLIEST_MANAGED_BLOCK: "65019285"
BACKFILL_START_BLOCK: "64920000"
```

As expected `us_central` CN was able to stream to `rfh01_test` and blocks starting to flow.

Also once **Autonomous Backfill** was triggered, it started backfilling from block `64920000` up to the first block it received at the time.

### Additional context

Even though that everything is working as expected, the BN since it was configure to Archive to S3, is attempting to upload it's batches but it can't, since range is not complete yet for each range.

producing this logs over and over again:

```
2025-12-05 21:55:13.905+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,830,000 was not found! Cannot proceed to upload archive block batch: 64,830,000 - 64,839,999
2025-12-05 21:55:13.905+0000 FINER   [org.hiero.block.node.backfill.BackfillPlugin handlePersisted] Received backfillType=AUTONOMOUS persisted notification for block=64928378
2025-12-05 21:55:13.905+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,830,000 - 64,839,999
2025-12-05 21:55:13.906+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,840,000 - 64,849,999
2025-12-05 21:55:13.906+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,840,000 was not found! Cannot proceed to upload archive block batch: 64,840,000 - 64,849,999
2025-12-05 21:55:13.906+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,840,000 - 64,849,999
2025-12-05 21:55:13.906+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,850,000 - 64,859,999
2025-12-05 21:55:13.906+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,850,000 was not found! Cannot proceed to upload archive block batch: 64,850,000 - 64,859,999
2025-12-05 21:55:13.906+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,850,000 - 64,859,999
2025-12-05 21:55:13.906+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,860,000 - 64,869,999
2025-12-05 21:55:13.907+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,860,000 was not found! Cannot proceed to upload archive block batch: 64,860,000 - 64,869,999
2025-12-05 21:55:13.907+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,860,000 - 64,869,999
2025-12-05 21:55:13.907+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,870,000 - 64,879,999
2025-12-05 21:55:13.907+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,870,000 was not found! Cannot proceed to upload archive block batch: 64,870,000 - 64,879,999
2025-12-05 21:55:13.907+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,870,000 - 64,879,999
2025-12-05 21:55:13.907+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,880,000 - 64,889,999
2025-12-05 21:55:13.907+0000 FINER   [org.hiero.block.node.verification.VerificationServicePlugin handleBackfilled] Verified backfill block items for block=64,928,379 with success=true
2025-12-05 21:55:13.907+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,880,000 was not found! Cannot proceed to upload archive block batch: 64,880,000 - 64,889,999
2025-12-05 21:55:13.907+0000 FINER   [org.hiero.block.node.messaging.BlockMessagingFacilityImpl lambda$sendBlockVerification$6] Sending block verification notification for block=64,928,379 blockSource=BACKFILL and success=true 
2025-12-05 21:55:13.907+0000 FINER   [org.hiero.block.node.backfill.BackfillPlugin handleVerification] Received verification notification for block 64928379
2025-12-05 21:55:13.907+0000 FINER   [org.hiero.block.node.blocks.files.recent.BlockFileRecentPlugin handleVerification] Persistence Handle verification started for block 64,928,379
2025-12-05 21:55:13.907+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,880,000 - 64,889,999
2025-12-05 21:55:13.908+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,890,000 - 64,899,999
2025-12-05 21:55:13.908+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,890,000 was not found! Cannot proceed to upload archive block batch: 64,890,000 - 64,899,999
2025-12-05 21:55:13.908+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,890,000 - 64,899,999
2025-12-05 21:55:13.908+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,900,000 - 64,909,999
2025-12-05 21:55:13.908+0000 FINER   [org.hiero.block.node.blocks.files.historic.BlockFileHistoricPlugin writeBlockOrFail] Wrote verified block 64,928,379 to file /opt/hiero/block-node/data/historic/staging/000/000/000/006/492/8/0000000000064928379.blk.zstd
2025-12-05 21:55:13.908+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,900,000 was not found! Cannot proceed to upload archive block batch: 64,900,000 - 64,909,999
2025-12-05 21:55:13.908+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,900,000 - 64,909,999
2025-12-05 21:55:13.909+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,910,000 - 64,919,999
2025-12-05 21:55:13.909+0000 FINER   [org.hiero.block.node.blocks.files.recent.BlockFileRecentPlugin writeBlockOrFail] Wrote verified block 64,928,379 to file /opt/hiero/block-node/data/live/000/000/000/006/492/8/0000000000064928379.blk.zstd
2025-12-05 21:55:13.909+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,910,000 was not found! Cannot proceed to upload archive block batch: 64,910,000 - 64,919,999
2025-12-05 21:55:13.909+0000 FINER   [org.hiero.block.node.blocks.files.recent.BlockFileRecentPlugin handleVerification] Persistence Handle verification finished for block 64928379, and it took 1466127 ns to complete
2025-12-05 21:55:13.909+0000 FINER   [org.hiero.block.node.messaging.BlockMessagingFacilityImpl lambda$sendBlockPersisted$8] Sending block persisted notification: PersistedNotification[blockNumber=64928379, succeeded=true, blockProviderPriority=2000, blockSource=BACKFILL]
2025-12-05 21:55:13.909+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,910,000 - 64,919,999
2025-12-05 21:55:13.909+0000 FINER   [org.hiero.block.node.backfill.BackfillPlugin handlePersisted] Received backfillType=AUTONOMOUS persisted notification for block=64928379
2025-12-05 21:55:13.909+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,920,000 - 64,929,999
2025-12-05 21:55:13.909+0000 FINER   [org.hiero.block.node.backfill.BackfillPlugin backfillGap] Successfully backfilled gap 64928370->64928379
2025-12-05 21:55:14.061+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,928,380 was not found! Cannot proceed to upload archive block batch: 64,920,000 - 64,929,999
2025-12-05 21:55:14.142+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,920,000 - 64,929,999
2025-12-05 21:55:14.142+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,930,000 - 64,939,999
2025-12-05 21:55:14.142+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,930,000 was not found! Cannot proceed to upload archive block batch: 64,930,000 - 64,939,999
2025-12-05 21:55:14.142+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,930,000 - 64,939,999
2025-12-05 21:55:14.143+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,940,000 - 64,949,999
2025-12-05 21:55:14.143+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,940,000 was not found! Cannot proceed to upload archive block batch: 64,940,000 - 64,949,999
2025-12-05 21:55:14.143+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,940,000 - 64,949,999
2025-12-05 21:55:14.143+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,950,000 - 64,959,999
2025-12-05 21:55:14.143+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,950,000 was not found! Cannot proceed to upload archive block batch: 64,950,000 - 64,959,999
2025-12-05 21:55:14.143+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,950,000 - 64,959,999
2025-12-05 21:55:14.143+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,960,000 - 64,969,999
2025-12-05 21:55:14.143+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,960,000 was not found! Cannot proceed to upload archive block batch: 64,960,000 - 64,969,999
2025-12-05 21:55:14.144+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,960,000 - 64,969,999
2025-12-05 21:55:14.144+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,970,000 - 64,979,999
2025-12-05 21:55:14.144+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,970,000 was not found! Cannot proceed to upload archive block batch: 64,970,000 - 64,979,999
2025-12-05 21:55:14.144+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,970,000 - 64,979,999
2025-12-05 21:55:14.144+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,980,000 - 64,989,999
2025-12-05 21:55:14.144+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,980,000 was not found! Cannot proceed to upload archive block batch: 64,980,000 - 64,989,999
2025-12-05 21:55:14.144+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,980,000 - 64,989,999
2025-12-05 21:55:14.144+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,990,000 - 64,999,999
2025-12-05 21:55:14.144+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,990,000 was not found! Cannot proceed to upload archive block batch: 64,990,000 - 64,999,999
2025-12-05 21:55:14.145+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,990,000 - 64,999,999
2025-12-05 21:55:14.145+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 65,000,000 - 65,009,999
2025-12-05 21:55:14.145+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 65,000,000 was not found! Cannot proceed to upload archive block batch: 65,000,000 - 65,009,999
2025-12-05 21:55:14.145+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 65,000,000 - 65,009,999
2025-12-05 21:55:14.145+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,320,000 - 64,329,999
2025-12-05 21:55:14.145+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,320,000 was not found! Cannot proceed to upload archive block batch: 64,320,000 - 64,329,999
2025-12-05 21:55:14.145+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,320,000 - 64,329,999
2025-12-05 21:55:14.145+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,330,000 - 64,339,999
2025-12-05 21:55:14.145+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,330,000 was not found! Cannot proceed to upload archive block batch: 64,330,000 - 64,339,999
2025-12-05 21:55:14.146+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,330,000 - 64,339,999
2025-12-05 21:55:14.146+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,340,000 - 64,349,999
2025-12-05 21:55:14.146+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,340,000 was not found! Cannot proceed to upload archive block batch: 64,340,000 - 64,349,999
2025-12-05 21:55:14.146+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,340,000 - 64,349,999
2025-12-05 21:55:14.146+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,350,000 - 64,359,999
2025-12-05 21:55:14.146+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,350,000 was not found! Cannot proceed to upload archive block batch: 64,350,000 - 64,359,999
2025-12-05 21:55:14.146+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,350,000 - 64,359,999
2025-12-05 21:55:14.146+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,360,000 - 64,369,999
2025-12-05 21:55:14.146+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,360,000 was not found! Cannot proceed to upload archive block batch: 64,360,000 - 64,369,999
2025-12-05 21:55:14.146+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,360,000 - 64,369,999
2025-12-05 21:55:14.147+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,370,000 - 64,379,999
2025-12-05 21:55:14.147+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,370,000 was not found! Cannot proceed to upload archive block batch: 64,370,000 - 64,379,999
2025-12-05 21:55:14.147+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,370,000 - 64,379,999
2025-12-05 21:55:14.147+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,380,000 - 64,389,999
2025-12-05 21:55:14.147+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,380,000 was not found! Cannot proceed to upload archive block batch: 64,380,000 - 64,389,999
2025-12-05 21:55:14.147+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,380,000 - 64,389,999
2025-12-05 21:55:14.147+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,390,000 - 64,399,999
2025-12-05 21:55:14.147+0000 WARNING [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask gatherAccessors] Historical block 64,390,000 was not found! Cannot proceed to upload archive block batch: 64,390,000 - 64,399,999
2025-12-05 21:55:14.147+0000 INFO    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Could not upload archive block batch: 64,390,000 - 64,399,999
2025-12-05 21:55:14.147+0000 FINE    [org.hiero.block.node.archive.s3.S3ArchivePlugin$UploadTask call] Uploading archive block batch: 64,400,000 - 64,409,999
```

### PR DESCRIPTION
**Pull request by AlfredoG87**
## Reviewer Notes

- Prevents unnecessary re-scheduling of batches.
- Prevents scheduling an archive task while the batch is not completely available.
- Improves UTs and Adds a new Not Available range scenario

## Related Issue(s)
Fixes #1941

### CODE REVIEW

File: block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java [hunk 1]
```diff
@@ -288,7 +309,7 @@ public Void call() throws S3ClientInitializationException, S3ResponseException,
                     }
                 }
             }
-            return null;
+            return nextBatchStartBlockNumber;
```
Comment (ata-nas) [inline block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java]: Not sure how I feel about this. The return was reserved for other purposes. This seems wasteful. The task could remove the pending just before exiting, again in a finally block.

File: block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java [hunk 2]
```diff
@@ -75,6 +79,8 @@ public class S3ArchivePlugin implements BlockNodePlugin, BlockNotificationHandle
     private ExecutorService executorService;
     /** A completion service for the active uploads. */
     private CompletionService<Void> activeUploads;
+    /** Tracks batch starts already queued to avoid duplicate scheduling. */
+    private final Set<Long> pendingBatchStarts = ConcurrentHashMap.newKeySet();
```
Comment (ata-nas) [inline block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java]: This might be a better option.
```suggestion
    private final Set<Long> pendingBatchStarts = new ConcurrentSkipListSet<>();
```

File: block-node/s3-archive/src/main/java/module-info.java [hunk 3]
```diff
@@ -18,6 +18,7 @@
     requires org.hiero.block.node.base;
     requires org.hiero.block.protobuf.pbj;
     requires com.github.spotbugs.annotations;
+    requires java.logging;
```
Comment (ata-nas) [inline block-node/s3-archive/src/main/java/module-info.java]: This should not be needed. I think this could have been mistakenly added?

File: block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java [hunk 4]
```diff
@@ -2,6 +2,7 @@
 package org.hiero.block.node.archive.s3;
 
 import static java.util.concurrent.locks.LockSupport.parkNanos;
+import static java.util.logging.Level.FINEST;
```
Comment (ata-nas) [inline block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java]: I think this import is possibly wrong.

File: block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java [hunk 5]
```diff
@@ -55,7 +58,7 @@
 /**
  * Unit tests for the {@link S3ArchivePlugin} class.
  */
-@Timeout(value = 5, unit = TimeUnit.SECONDS)
+@Timeout(value = 15, unit = TimeUnit.SECONDS)
```
Comment (ata-nas) [inline block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java]: Curious, why the increase? This is somewhat worry-some.

File: block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/logging/TestLogHandler.java
[the remark this answers is not in the document]
Comment (AlfredoG87) [reply block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/logging/TestLogHandler.java]: Same answer as above.

File: block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java (hunk 5 above)
Comment (AlfredoG87) [reply block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java]:
```
import static java.util.logging.Level.FINEST;
                       ^
  (package java.util.logging is declared in module java.logging, but module org.hiero.block.node.archive.s3cloud does not read it)
```

reverting back to include the dep in the testModuleInfo in the gradle build for the module.

File: block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java [hunk 6]
```diff
@@ -68,9 +71,19 @@ class S3ArchivePluginTest extends PluginTestBase<S3ArchivePlugin, ExecutorServic
...
+
     @SuppressWarnings("resource")
     public S3ArchivePluginTest() throws GeneralSecurityException, IOException, MinioException {
         super(Executors.newSingleThreadExecutor(), Executors.newSingleThreadScheduledExecutor());
+        // set-up logger
+        Logger logger = Logger.getLogger(S3ArchivePlugin.class.getName());
+        System.out.println("logger = " + logger);
+        logHandler = new TestLogHandler();
+        logger.addHandler(logHandler);
+        logger.setLevel(FINEST);
```
[the remark this answers is not in the document]
Comment (ata-nas) [reply block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java]: If we have to mock an executor, we must simply use the blocking executor we have. It's whole purpose is to make tests non flaky and give us the ability to assert.

To your second point, I agree we should not be asserting based on exposing internal state. This begs the question, what are we actually testing for? What is the user story behind the test? If our code is good, we should always be able to easily assert end results.

[the remark this answers is not in the document]
Comment (AlfredoG87) [reply block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java]: In this particular test assertion is preventing re-scheduling of a job task to prevent a regression, is good to have good coverage that covers previous bugs. Using a real executor is not gonna cut it, since we need to be able to access its internal state. I guess we could use reflection. but why overcomplicate things? I don't see us changing of Log Facade and this being an issue any time soon.

**Review by ata-nas — APPROVED** [review]
Let's proceed with what we have. As mentioned, we need to tackle project wide log asserts in a separate issue. When scheduling the s3 rework, most of the existing code could be rendered obsolete.
