### PR TITLE
fix: hard shutdown of the producer causes exception when another is connected

### LINKED ISSUE #932: Add Publisher Tests
### Story Form

As a Block Node Developer
I want to have enough code coverage on the Publisher Plugin
So that I can confidently use and deploy the application in production environments.

### Technical Notes

.

### LINKED ISSUE #1053: Hard shutdown of the producer causes exception when another is connected.
### Description

Hard shutdown of a producer causes the plugin to not properly remove it from the list of sessions. This cause problems when another is connected and reaches the lastest available block. This causes the newer producer to throw exception and closes the connection. Further more this keeps the plugin in a deadlock, where it denies new producers when they reach the latest available block.

### Steps to Reproduce

1. Run the block-node application
2. Run a publisher for couple of seconds, until it reaches more than one send blocks
3. Perform a hard stop, using IDE UI for example
4. Start a second publisher and observe.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by georgi-l95**
## Reviewer Notes
This PR resolves a case where, after hard shutdown of a producer the publisher stops accepting new producers.
Also moves around and cleans up the `suites`, by separating utils that can be used everywhere.

## Related Issue(s)
Fixes #1053 
Fixes #932

### CODE REVIEW

File: block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java [hunk 1]
```diff
@@ -309,7 +308,7 @@ private void sendResponse(final PublishStreamResponse response) {
 
         try {
             responsePipeline.onNext(response);
-        } catch (UncheckedIOException e) {
+        } catch (RuntimeException e) {
```
Comment (georgi-l95) [inline block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java:311]: It seems that when the exception is lower than RuntimeException (UncheckedIO, Socket) we don't catch all cases of failure. Althouth not sure if the whole flow is incorrect, meaning that we should call onNext and be done with it, if any error occurs on the helidon plugin side, it should trigger onError, but that is not the case. Therefore this is the only way (for now) to avoid locking plugin from accepting new producers in this edge case.

Comment (AlfredoG87) [reply block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java:311]: Yes Indeed seems like a bug on Helidon.
@mattp-swirldslabs complained about this and I believe there is an outstanding Helidon Issue raised about this. 
Was able to find this one, seems related but not 100% sure if is the same thing 🤔 
https://github.com/helidon-io/helidon/issues/9496

**Review by AlfredoG87 — APPROVED** [review]
LGTM, let me know when rebased and ready for review so I can re-review (changes) and approve.

File: suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    }
+
+    /**
+     * Creates a SingleBlockRequest to retrieve a specific block.
+     *
+     * @param blockNumber The block number to retrieve
+     * @param latest Whether to retrieve the latest block
+     * @return A SingleBlockRequest object
+     */
+    public static BlockRequest createSingleBlockRequest(long blockNumber, boolean latest) {
```
Comment (Nana-EC) [inline suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java:28]: Please note renaming on protobuf size and align there
```suggestion
    public static BlockRequest createGetBlockRequest(long blockNumber, boolean latest) {
```

File: suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+    /**
+     * Retrieves a single block using the Block Node API.
+     *
+     * @param blockNumber The block number to retrieve
+     * @param allowUnverified A flag to indicate that the requested block may be sent without
+     *   verifying its `BlockProof`
+     * @return The SingleBlockResponse from the API
+     */
+    public static BlockResponse getSingleBlock(
```
Comment (Nana-EC) [inline suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java:44]:
```suggestion
    public static BlockResponse getBlock(
```

File: block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java (hunk 1 above)
Comment (Nana-EC) [reply block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java:311]: Nice catch

**Review by Nana-EC — COMMENTED** [review]
Looking good.
Please note the naming changes. Best to keep naming convention in line with API

File: suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java
Comment (ata-nas) [inline suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java:1]: +1 for this reusable utility. 👍

**Review by ata-nas — DISMISSED** [review]
LG @georgi-l95

File: suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java (hunk 2 above)
Comment (georgi-l95) [reply suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java]: Thanks, changed 👍

File: suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java (hunk 3 above)
Comment (georgi-l95) [reply suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java]: Thanks, changed 👍

**Review by ata-nas — DISMISSED** [review]
🔥

**Review by AlfredoG87 — APPROVED** [review]
re-approving!

**Review by AlfredoG87 — APPROVED** [review]

**Review by jsync-swirlds — APPROVED** [review]
