### PR TITLE
test: Files Recent Plugin Unit Tests Pt.2

### LINKED ISSUE #946: Files Recent Plugin Unit Tests Pt.2
### Story Form

As a Block Node Developer
I want to have unit tests for the `Files Recent` Plugin
So that I have confidence in existing logic and catch regressions

### Technical Notes

- part 2 of unit tests for the `Files Recent` Plugin

### PR DESCRIPTION
**Pull request by ata-nas**
## Reviewer Notes

- part 2 of unit tests for the `Files Recent` Plugin

## Related Issue(s)

Closes #946

### CODE REVIEW

File: common/src/test/java/org/hiero/block/common/utils/PreconditionsTest.java [hunk 1]
```diff
@@ -459,6 +480,189 @@ void testRequirePositivePowerOf10Fail(final int toTest) {
...
     }
 
+    /**
+     * This test aims to verify that the
+     * {@link Preconditions#requireRegularFile(Path)} will return the input
+     * 'toTest' parameter if the regular file check passes.
+     * Test includes overloads.
+     */
+    @Test
+    void testSuccessfulRequireRegularFile() throws IOException {
```
Comment (jasperpotts) [inline common/src/test/java/org/hiero/block/common/utils/PreconditionsTest.java:490]: It would be good for test stuff to move out of common main module. We can add a common test fixtures module if needed across apps, otherwise add to app fixtures module.

**Review by jasperpotts — APPROVED** [review]
