### PR TITLE
fix: Moved GRPC services over to use PBJ generated ones

### LINKED ISSUE #1088: Replace protoc gRPC implementations with PBJ versions
### Story Form

As a Block Node Engineer
I want to use PBJ generated classes and avoid protoc generated classes
So that I have no dependencies on protoc and can remove that step from the build

### Technical Notes

An earlier issue removed the protoc gRPC stubs and switched to PBJ stubs, but the refactor somehow switched everything back to protoc stubs.  We would very much like to remove the protoc compile step from the build entirely so we don't have the dependency tree in the deployed system and also avoid accidentally importing the wrong version of protobuf-defined classes.

### PR DESCRIPTION
**Pull request by jasperpotts**
## Reviewer Notes
Stops exporting protoc to anything other than simulator and suites

## Related Issue(s)
Fixes #1088

### CODE REVIEW

File: block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java [hunk 1]
```diff
@@ -6,20 +6,12 @@
...
-import com.hedera.pbj.runtime.io.buffer.Bytes;
 import com.swirlds.metrics.api.Counter;
-import edu.umd.cs.findbugs.annotations.NonNull;
-import java.util.Arrays;
-import java.util.List;
+import org.hiero.block.api.BlockAccessServiceInterface;
 import org.hiero.block.api.BlockRequest;
 import org.hiero.block.api.BlockResponse;
 import org.hiero.block.api.BlockResponse.Code;
 // PBJ doesn't generate GRPC stubs for some reason, also the proto file is broken when PBJ compiles it...
```
Comment (jsync-swirlds) [inline block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java:14]: Might want to remove this comment as well.

File: block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java [hunk 2]
```diff
@@ -171,21 +128,17 @@ static class SubscribeBlockStreamHandler
...
         private final ExecutorCompletionService<BlockStreamSubscriberSession> streamSessions;
 
-        private SubscribeBlockStreamHandler(
-                @NonNull final BlockNodeContext context, @NonNull final SubscriberServicePlugin plugin) {
+        private SubscribeBlockStreamHandler(@NonNull final BlockNodeContext context) {
             this.context = requireNonNull(context);
-            this.plugin = requireNonNull(plugin);
             this.openSessions = new ConcurrentSkipListMap<>();
-            virtualThreadExecutor = context.threadPoolManager().getVirtualThreadExecutor(null);
+            virtualThreadExecutor = context.threadPoolManager().getVirtualThreadExecutor("SubscribeBlockStreamHandler");
```
Comment (jsync-swirlds) [inline block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java:141]: This was null on purpose, so we don't create unique executors for every single request.

**Review by jsync-swirlds — DISMISSED** [review]
A couple of non-blocking items.

Thanks for tackling this.

**Review by AlfredoG87 — APPROVED** [review]
LGTM, other than the comments leaved by @jsync-swirlds 
Also spotless is compalining.

File: block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java (hunk 2 above)
Comment (Nana-EC) [reply block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java:141]: Maybe we should make it more explicit. 
Setting a name hiding implications of executor service and handler relationships is bound to be missed.
Not for this PR but should that interface be made more explicit with an enum that forces clear specification of intention by a dev when calling this?

**Review by Nana-EC — DISMISSED** [review]
LG, gets us closer to no more protoc

**Review by georgi-l95 — APPROVED** [review]

File: block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java (hunk 2 above)
Comment (jsync-swirlds) [reply block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java:141]: Possibly.  It's very tricky to define an API that's both clean for routine use and clear for every option.
The impacts of thread name, in particular, because it's a debugging detail, are specific to the implementation (name isn't guaranteed to be used at all), so it's a very difficult item to define and document properly.
The thread name item is particularly pernicious as we've made some somewhat flawed assumptions all over the codebase after switching to this thread manager model, and the name parameter ties into most of those.
Certainly we can document these things better; though we need to be careful that we don't document _implementation_ details in the _API_ documents.

Comment (jasperpotts) [reply block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java]: I changed it as it was flagged as error in IntelliJ as the method parameter is marked as `@NotNull` so it is flagged when you pass null. Maybe you can do another PR and either remove the @NotNull and document the null behavior or remove the special null handling and add a extra method for that specific use case. I like the latter better I think.

File: block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java (hunk 1 above)
Comment (jasperpotts) [reply block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java]: done

File: block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java (hunk 2 above)
Comment (jsync-swirlds) [reply block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java]: I'll send a PR to fix the annotation, and perhaps also to try to explain this implementation detail in the default implementation class.

**Comment by jsync-swirlds** [comment]
Complete side note, but github is not verifying the signature on your commits; so there may be a setup issue somewhere.
image

File: block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java [hunk 3]
```diff
@@ -99,11 +92,18 @@ private BlockResponse handleBlockRequest(BlockRequest request) {
     }
 
     // ==== BlockNodePlugin Methods ====================================================================================
+
+    /**
+     * {@inheritDoc}
+     */
```
Comment (jsync-swirlds) [inline block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java:98]: Just curious, why do we keep adding these?
The javadoc will be duplicated properly when there is no comment at all; so this is just extra clutter.

**Review by jsync-swirlds — APPROVED** [review]

**Review by AlfredoG87 — APPROVED** [review]

File: block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java (hunk 3 above)
Comment (jasperpotts) [reply block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java:98]: if you have "Render All Doc Comments" on in IntelliJ then you get comments in for methods if you include inherit. 

Screenshot 2025-05-20 at 3 07 16 PM
