### PR TITLE
fix: Clear `queueByMap` When Verification Fails

### LINKED ISSUE #1565: Clear `queueByMap` When Verification Fails
### Story Form

As a Block Node Operator/User/Engineer
I want to properly manage the internal state of the publisher manager
So that the publisher functionality will work accordingly

### Technical Notes

- the publisher manager has to clear all queues by block number when verification fails

### PR DESCRIPTION
**Pull request by ata-nas**
## Reviewer Notes

* Clear the queueByMap on failed verficiations
* Added todos with considerations for upcoming changes
* Improved the handlerIsEnding method with a CAS for the next unstreamed

## Related Issue(s)

Fixes #1565

### CODE REVIEW

File: block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java [hunk 1]
```diff
@@ -392,25 +395,24 @@ public void handlerIsEnding(final long blockNumber, final long handlerId) {
...
-                    // from the queueByBlockMap, as it will be in an incomplete
-                    // state when the handler shuts down, which happens on the
-                    // same thread that called this method immediately after.
-                    // It is important that this queue is removed from the
-                    // queueByBlockMap, because it is not guaranteed that the
-                    // same publisher will supply the next unstreamed block we
-                    // just decremented.
-                    queue.clear();
-                }
+            nextUnstreamedBlockNumber.compareAndSet(blockNumber + 1, blockNumber);
```
Comment (Nana-EC) [inline block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:398]: nit: the previous use of `decrementAndGet()` made it clear that the `blockNumber` was being decremented. 
It's a bit more foggy now but can be worked out.
This is a good location for a good comment covering why we decrement by this amount and in this order

**Review by Nana-EC — APPROVED** [review]
LG.
Could use more comments at key locations but this is non blocking for this PR

File: block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java (hunk 1 above)
Comment (jsync-swirlds) [reply block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:421]: Comment added.

File: block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java [hunk 2]
```diff
@@ -146,6 +150,26 @@ public void removeHandler(final long handlerId) {
...
+        // Remove items until we find a block proof or the queue is empty.
+        while (last != null && !(last.blockItems().getLast().hasBlockProof())) {
+            queue.removeLast();
+            itemsRemoved++;
+            last = queue.peekLast();
+        }
+        // @todo(1416) add an "items discarded" metric.
+        return itemsRemoved > 0;
+    }
+
```
Comment (jsync-swirlds) [inline block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java:172]: Note, Added this method (and called in two places) because the smaller change failed tests due to being _too_ aggressive at queue clearing.  This fixes that and also makes the general case more correct.

**Review by jsync-swirlds — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
